# Generated by Django 5.2.5 on 2025-11-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_number',
        ),
    ]
